name: kts

services:
  backend:
    image: 767397975047.dkr.ecr.ap-south-1.amazonaws.com/kts/backend:latest
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
